[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
fungstake = "J4Awz2tgfFUqDZorkaT3FMnV5Hy6vh8AbwvAMLNzpKJ1"
vault = "9grg8RG2prncny136yjDMy5BZcwhB4NvqGMGDFs7QtKy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
build-with-so = "mkdir -p $PWD/target/deploy && anchor build"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
