[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
fungstake = "5VgFt7VaM9eMchXbhLmepFvgwVBniab4PUYBskcYesML"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
build-with-so = "mkdir -p $PWD/target/deploy && anchor build"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
