[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
fungstake = "J4Awz2tgfFUqDZorkaT3FMnV5Hy6vh8AbwvAMLNzpKJ1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
build-with-so = "mkdir -p $PWD/target/deploy && anchor build && ln -s $HOME/.cargo/target/sbf-solana-solana/release/fungstake.so $PWD/target/deploy/fungstake.so"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
